### PR TITLE
Add Google Analytics script

### PR DESCRIPTION
**Pull request by neobrain**
Not really sure if I did that correctly, though :p 

This allows us to track visitor stats etc, and eventually enable ads on our homepage.

### CODE REVIEW

**Comment by chinhodado** [comment]
This should be added to the `<head>` element, not the root `<html>`.

**Comment by neobrain** [comment]
Thanks for the info, fixed that.

**Comment by archshift** [comment]
Ship it!

**Comment by neobrain** [comment]
Uh, right. Kinda forgot about this :p

**Pull request merged**
