### PR TITLE
Added Meta-Viewport info.

### PR DESCRIPTION
**Pull request by isaacrg**
This should resolve most concerns about responsive views on mobile.

### CODE REVIEW

**Comment by isaacrg** [comment]
More info on the Viewport meta tag [here on MDN](https://developer.mozilla.org/en/docs/Mozilla/Mobile/Viewport_meta_tag).

**Comment by archshift** [comment]
Could you post a few screenshots of how this change makes the site look on different mobile browsers?

**Comment by isaacrg** [comment]
@archshift 

I have posted comparison images in an album [here](http://imgur.com/a/VcgMO). Note that there is no change in appearance for desktop browsers, and the top bar now matches the rest of the page for font size.

The site I used for demonstrating the proposed change was [isaacrg.me/citra-emu.github.io/](http://isaacrg.me/citra-emu.github.io/)

**Comment by isaacrg** [comment]
@archshift Should this be merged?

**Comment by isaacrg** [comment]
Cancelling

**Pull request closed without merging**
